export const ROUTE_ROOT_PAGE = '/'
export const ROUTE_HOME_PAGE = '/home'
export const ROUTE_GUEST_PAGE = '/guest'
export const ROUTE_SIGN_UP_PAGE = '/sign-up'
export const ROUTE_SIGN_IN_PAGE = '/sign-in'
export const ROUTE_SIGN_OUT_PAGE = '/sign-out'
export const ROUTE_403_ERROR_PAGE = '/403'
